system_paths:
    basepath: /home/acpaquette/Desktop/
    inputfile_path: /home/acpaquette/autocnet/autocnet/examples/Apollo15/
    outputfile_path: /home/acpaquette/autocnet/autocnet/examples/Apollo15/

extract_features:
    method: sift
    extractor_parameters:
        nfeatures: 1000

match_features:
    k: 50

# Any clean keys being passed in requires a method to have been used on the candidate graph object
# before the key can be passed in

ratio_check:
    clean_keys:
        -

# Keyword arguments
    ratio: 0.8
    mask_name: None
    single: False


fundamental_matrices:
    clean_keys:
        - ratio
        - symmetry

# Keyword arguments
    method: ransac
    reproj_threshold: 5.0
    confidence: 0.99

subpixel_register:
    clean_keys:
        - ratio
    template_size: 5
    threshold: 0.8
    search_size: 15
    max_x_shift: 1.0
    max_y_shift: 1.0
    tiled: False

# Keyword arguments
    upsampling: 16
    error_check: False

suppress:
    clean_keys:
        - ratio

# Keyword arguments
    min_radius: 2
    k: 50
    error_k: 0.1

cnet_conversion:
    clean_keys:
        - subpixel
to_isis:
    networkid: None
    targetname: Moon
    description: None
    username: DEFAULTUSERNAME
